UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVILIZATION_FAIRY_QUEENDOM_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVILIZATION_FAIRY_QUEENDOM_DESCRIPTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVILIZATION_FAIRY_QUEENDOM_ADJECTIVE"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_1"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_TRAIT_CIVILIZATION_BUILDING_FAIRYCO_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_TRAIT_CIVILIZATION_UNIT_THE_FAIRIES_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_TRAIT_ONE_NIGHT_CITY_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_TRAIT_ONE_NIGHT_CITY_DESCRIPTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_MALE_1"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_MALE_2"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_MALE_3"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_MALE_4"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_FEMALE_1"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_FEMALE_2"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_FEMALE_3"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_FEMALE_4"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CITIZEN_FAIRY_QUEENDOM_FEMALE_5"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_FAIRY_QUEENDOM_HISTORY"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVINFO_FAIRY_QUEENDOM_HISTORY"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_FAIRY_QUEENDOM_POPULATION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVINFO_FAIRY_QUEENDOM_POPULATION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_2"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_3"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_4"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_5"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_6"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_7"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_8"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_9"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_CIVLIZATION_FAIRY_QUEENDOM_CITY_10"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_BUILDING_DESSERT_HOUSE_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_BUILDING_DESSERT_HOUSE_DESCRIPTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_BUILDING_GODDESS_STATUE_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_BUILDING_GODDESS_STATUE_DESCRIPTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_RESOURCE_DESSERT_1_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_RESOURCE_DESSERT_2_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_RESOURCE_DESSERT_3_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_RESOURCE_DESSERT_4_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_RESOURCE_DESSERT_5_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_RESOURCE_DESSERT_6_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_LEADER_MS_HUMAN_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_TRAIT_INSIDE_PINK_ITS_ALL_BLACK_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_TRAIT_INSIDE_PINK_ITS_ALL_BLACK_DESCRIPTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_UNIT_THE_FAIRIES_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_UNIT_THE_FAIRIES_DESCRIPTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_DISTRICT_FAIRYCO_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_DISTRICT_FAIRYCO_DESCRIPTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_DISTRICT_FAIRYCO_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_DISTRICT_MINE_FOOD"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_DISTRICT_QUARRY_FOOD"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_DISTRICT_DISTRICT_FOOD"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_DISTRICT_FAIRYCO_CITY_CENTER_PRODUCTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_DISTRICT_FAIRYCO_CITY_CENTER_FOOD"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_LEADER_MS_HUMAN_QUOTE"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_AGENDA_UNITED_NATIONS_ARBITRATOR_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_AGENDA_UNITED_NATIONS_ARBITRATOR_DESCRIPTION"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_TRAIT_LEADER_BUILDING_DESSERT_HOUSE_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_TRAIT_LEADER_BUILDING_GODDESS_STATUE_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_UNIT_BUILDER_NAME"

UPDATE BaseGameText SET Text=""
WHERE Tag="LOC_UNIT_BUILDER_DESCRIPTION"

